openapi: 3.0.0
info:
  version: 1.0.0
  title: Health Reporting API
  description: API to return health check report status and diagnosis
paths:
  /reportResultLambda:
    get:
      summary: Get result of report for given report id
      description: Returns result of report and diagnosis for available reports 
      responses:
        '200':
          description: Successfully returned report status
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - reportId
                  properties:
                    reportId:
                      type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
